// KonkoorBaz Realistic Persian Mock Data

import type { Listing, User, Book, Publisher } from "./types";

// ===== Mock Publishers =====
export const mockPublishers: Publisher[] = [
  { _id: "pub1", name: "گاج", slug: "gaj", logo: "" },
  { _id: "pub2", name: "قلم‌چی", slug: "ghalam-chi", logo: "" },
  { _id: "pub3", name: "خیلی سبز", slug: "kheili-sabz", logo: "" },
  { _id: "pub4", name: "مگا بوک", slug: "mega-book", logo: "" },
  { _id: "pub5", name: "نشر الگو", slug: "nashr-olgu", logo: "" },
  { _id: "pub6", name: "مبتکران", slug: "mobtakeran", logo: "" },
  { _id: "pub7", name: "کانون فرهنگی آموزش", slug: "kanoon", logo: "" },
  { _id: "pub8", name: "مدرسه", slug: "madreseh", logo: "" },
  { _id: "pub9", name: "مهروماه", slug: "mehr-o-mah", logo: "" },
  { _id: "pub10", name: "میکرو طبقه‌بندی", slug: "micro", logo: "" },
  { _id: "pub11", name: "نردبان", slug: "nardebaan", logo: "" },
  { _id: "pub12", name: "خوشخوان", slug: "khoshkhaan", logo: "" },
];

// ===== Mock Users =====
export const mockUsers: User[] = [
  {
    _id: "u1",
    name: "محمد رضایی",
    phone: "0912***4567",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2025-09-15T10:00:00Z",
    province: "تهران",
    city: "تهران",
    rating: 4.8,
    totalSales: 23,
    totalPurchases: 5,
  },
  {
    _id: "u2",
    name: "زهرا احمدی",
    phone: "0935***8901",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2025-11-20T14:30:00Z",
    province: "اصفهان",
    city: "اصفهان",
    rating: 4.9,
    totalSales: 45,
    totalPurchases: 12,
  },
  {
    _id: "u3",
    name: "امیرعلی حسینی",
    phone: "0919***2345",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2026-01-10T09:15:00Z",
    province: "فارس",
    city: "شیراز",
    rating: 4.6,
    totalSales: 15,
    totalPurchases: 8,
  },
  {
    _id: "u4",
    name: "فاطمه موسوی",
    phone: "0922***6789",
    avatar: "",
    role: "user",
    isVerified: false,
    createdAt: "2026-03-05T16:45:00Z",
    province: "خراسان رضوی",
    city: "مشهد",
    rating: 4.3,
    totalSales: 7,
    totalPurchases: 3,
  },
  {
    _id: "u5",
    name: "رضا کریمی",
    phone: "0936***0123",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2026-02-18T11:20:00Z",
    province: "تهران",
    city: "کرج",
    rating: 4.7,
    totalSales: 31,
    totalPurchases: 9,
  },
  {
    _id: "u6",
    name: "نازنین عباسی",
    phone: "0918***4567",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2025-12-01T08:00:00Z",
    province: "آذربایجان شرقی",
    city: "تبریز",
    rating: 5.0,
    totalSales: 52,
    totalPurchases: 18,
  },
  {
    _id: "u7",
    name: "حسین نوری",
    phone: "0913***8910",
    avatar: "",
    role: "user",
    isVerified: true,
    createdAt: "2026-04-12T13:00:00Z",
    province: "مازندران",
    city: "ساری",
    rating: 4.5,
    totalSales: 11,
    totalPurchases: 6,
  },
];

// ===== Mock Books (catalogue) =====
export const mockBooks: Book[] = [
  {
    _id: "b1",
    title: "زیست‌شناسی جامع کنکور",
    author: "اشکان هاشمی",
    publisher: mockPublishers[0],
    field: "experimental",
    grade: "konkoor",
    subject: "biology",
    originalPrice: 980000,
    coverImage: "",
  },
  {
    _id: "b2",
    title: "ریاضی تجربی جامع",
    author: "مهدی امینی‌راد",
    publisher: mockPublishers[1],
    field: "experimental",
    grade: "konkoor",
    subject: "math",
    originalPrice: 850000,
    coverImage: "",
  },
  {
    _id: "b3",
    title: "فیزیک پایه دوازدهم",
    author: "محمد عبدالهی",
    publisher: mockPublishers[2],
    field: "experimental",
    grade: "12",
    subject: "physics",
    originalPrice: 720000,
    coverImage: "",
  },
  {
    _id: "b4",
    title: "شیمی جامع کنکور",
    author: "بهمن بازرگانی",
    publisher: mockPublishers[0],
    field: "experimental",
    grade: "konkoor",
    subject: "chemistry",
    originalPrice: 920000,
    coverImage: "",
  },
  {
    _id: "b5",
    title: "ادبیات فارسی جامع",
    author: "علی‌اصغر حسینی",
    publisher: mockPublishers[4],
    field: "experimental",
    grade: "konkoor",
    subject: "persian",
    originalPrice: 650000,
    coverImage: "",
  },
  {
    _id: "b6",
    title: "عربی کامل کنکور",
    author: "حسین ادیب",
    publisher: mockPublishers[1],
    field: "experimental",
    grade: "konkoor",
    subject: "arabic",
    originalPrice: 580000,
    coverImage: "",
  },
  {
    _id: "b7",
    title: "هندسه تحلیلی و جبر خطی",
    author: "احمد صادقی",
    publisher: mockPublishers[5],
    field: "mathematics",
    grade: "12",
    subject: "geometry",
    originalPrice: 780000,
    coverImage: "",
  },
  {
    _id: "b8",
    title: "حسابان دوازدهم",
    author: "مصطفی باقری",
    publisher: mockPublishers[2],
    field: "mathematics",
    grade: "12",
    subject: "math",
    originalPrice: 690000,
    coverImage: "",
  },
  {
    _id: "b9",
    title: "تاریخ ایران و جهان",
    author: "مریم افشار",
    publisher: mockPublishers[7],
    field: "humanities",
    grade: "konkoor",
    subject: "history",
    originalPrice: 560000,
    coverImage: "",
  },
  {
    _id: "b10",
    title: "فلسفه و منطق جامع",
    author: "کامران رحیمی",
    publisher: mockPublishers[4],
    field: "humanities",
    grade: "konkoor",
    subject: "philosophy",
    originalPrice: 620000,
    coverImage: "",
  },
  {
    _id: "b11",
    title: "زبان انگلیسی جامع کنکور",
    author: "فرشید یوسفی",
    publisher: mockPublishers[0],
    field: "experimental",
    grade: "konkoor",
    subject: "english",
    originalPrice: 750000,
    coverImage: "",
  },
  {
    _id: "b12",
    title: "دین و زندگی جامع",
    author: "سعید محمدی",
    publisher: mockPublishers[1],
    field: "experimental",
    grade: "konkoor",
    subject: "religion",
    originalPrice: 480000,
    coverImage: "",
  },
  {
    _id: "b13",
    title: "فیزیک پایه دهم",
    author: "رضا ناظمی",
    publisher: mockPublishers[2],
    field: "experimental",
    grade: "10",
    subject: "physics",
    originalPrice: 580000,
    coverImage: "",
  },
  {
    _id: "b14",
    title: "ریاضیات گسسته",
    author: "علی مقدم",
    publisher: mockPublishers[5],
    field: "mathematics",
    grade: "12",
    subject: "discrete-math",
    originalPrice: 520000,
    coverImage: "",
  },
  {
    _id: "b15",
    title: "مبانی هنرهای تجسمی",
    author: "ندا شریفی",
    publisher: mockPublishers[7],
    field: "art",
    grade: "konkoor",
    subject: "art-basics",
    originalPrice: 450000,
    coverImage: "",
  },
  {
    _id: "b16",
    title: "جغرافیای ایران و جهان",
    author: "حمید نوروزی",
    publisher: mockPublishers[8],
    field: "humanities",
    grade: "konkoor",
    subject: "geography",
    originalPrice: 490000,
    coverImage: "",
  },
  {
    _id: "b17",
    title: "روان‌شناسی جامع کنکور",
    author: "لیلا شهبازی",
    publisher: mockPublishers[1],
    field: "humanities",
    grade: "konkoor",
    subject: "psychology",
    originalPrice: 540000,
    coverImage: "",
  },
  {
    _id: "b18",
    title: "شیمی پایه یازدهم",
    author: "بهمن بازرگانی",
    publisher: mockPublishers[0],
    field: "experimental",
    grade: "11",
    subject: "chemistry",
    originalPrice: 680000,
    coverImage: "",
  },
  {
    _id: "b19",
    title: "زیست‌شناسی پایه دهم",
    author: "اشکان هاشمی",
    publisher: mockPublishers[2],
    field: "experimental",
    grade: "10",
    subject: "biology",
    originalPrice: 620000,
    coverImage: "",
  },
  {
    _id: "b20",
    title: "جامعه‌شناسی جامع",
    author: "پریسا نیک‌خواه",
    publisher: mockPublishers[4],
    field: "humanities",
    grade: "konkoor",
    subject: "sociology",
    originalPrice: 470000,
    coverImage: "",
  },
];

// ===== Mock Listings =====
export const mockListings: Listing[] = [
  {
    _id: "l1",
    book: mockBooks[0],
    seller: mockUsers[0],
    price: 450000,
    originalPrice: 980000,
    condition: {
      grade: "excellent",
      highlighting: true,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: true,
      hasSupplement: false,
    },
    images: [{ _id: "img1", url: "", alt: "زیست‌شناسی جامع کنکور گاج", isPrimary: true }],
    description: "کتاب تمیز و سالم، فقط چند صفحه هایلایت شده. DVD آموزشی هم داره.",
    year: 1404,
    edition: 12,
    city: "تهران",
    province: "تهران",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 342,
    favorites: 28,
    status: "active",
    createdAt: "2026-07-10T14:30:00Z",
    updatedAt: "2026-07-10T14:30:00Z",
  },
  {
    _id: "l2",
    book: mockBooks[1],
    seller: mockUsers[1],
    price: 520000,
    originalPrice: 850000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: true,
      tornPages: false,
      missingPages: false,
      answersCompleted: true,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img2", url: "", alt: "ریاضی تجربی جامع قلم‌چی", isPrimary: true }],
    description: "تست‌ها پاسخ داده شده ولی کتاب سالمه. یادداشت‌های مفید توی حاشیه دارم.",
    year: 1404,
    edition: 8,
    city: "اصفهان",
    province: "اصفهان",
    shippingAvailable: true,
    pickupAvailable: false,
    isBundle: false,
    priceIndicator: "fair",
    views: 189,
    favorites: 15,
    status: "active",
    createdAt: "2026-07-09T11:00:00Z",
    updatedAt: "2026-07-09T11:00:00Z",
  },
  {
    _id: "l3",
    book: mockBooks[2],
    seller: mockUsers[2],
    price: 280000,
    originalPrice: 720000,
    condition: {
      grade: "like-new",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: true,
      hasSupplement: true,
    },
    images: [{ _id: "img3", url: "", alt: "فیزیک پایه دوازدهم خیلی سبز", isPrimary: true }],
    description: "خریدم ولی از یکی دیگه استفاده کردم. اصلاً باز نشده تقریباً.",
    year: 1405,
    edition: 15,
    city: "شیراز",
    province: "فارس",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 567,
    favorites: 45,
    status: "active",
    createdAt: "2026-07-11T09:20:00Z",
    updatedAt: "2026-07-11T09:20:00Z",
  },
  {
    _id: "l4",
    book: mockBooks[3],
    seller: mockUsers[3],
    price: 550000,
    originalPrice: 920000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img4", url: "", alt: "شیمی جامع کنکور گاج", isPrimary: true }],
    description: "هایلایت شده ولی خیلی تمیز. برای مرور عالیه.",
    year: 1404,
    edition: 10,
    city: "مشهد",
    province: "خراسان رضوی",
    shippingAvailable: true,
    pickupAvailable: false,
    isBundle: false,
    priceIndicator: "fair",
    views: 234,
    favorites: 19,
    status: "active",
    createdAt: "2026-07-08T16:00:00Z",
    updatedAt: "2026-07-08T16:00:00Z",
  },
  {
    _id: "l5",
    book: mockBooks[4],
    seller: mockUsers[4],
    price: 250000,
    originalPrice: 650000,
    condition: {
      grade: "excellent",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img5", url: "", alt: "ادبیات فارسی جامع نشر الگو", isPrimary: true }],
    description: "کاملاً سالم و تمیز. بدون هیچ خط‌خوردگی.",
    year: 1404,
    edition: 6,
    city: "کرج",
    province: "البرز",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 412,
    favorites: 33,
    status: "active",
    createdAt: "2026-07-07T10:45:00Z",
    updatedAt: "2026-07-07T10:45:00Z",
  },
  {
    _id: "l6",
    book: mockBooks[5],
    seller: mockUsers[5],
    price: 380000,
    originalPrice: 580000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: true,
      tornPages: false,
      missingPages: false,
      answersCompleted: true,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img6", url: "", alt: "عربی کامل کنکور قلم‌چی", isPrimary: true }],
    description: "تست‌ها جواب داده شده. یادداشت‌های کنار صفحه خیلی به درد می‌خوره.",
    year: 1403,
    edition: 7,
    city: "تبریز",
    province: "آذربایجان شرقی",
    shippingAvailable: true,
    pickupAvailable: false,
    isBundle: false,
    priceIndicator: "high",
    views: 156,
    favorites: 8,
    status: "active",
    createdAt: "2026-07-06T13:30:00Z",
    updatedAt: "2026-07-06T13:30:00Z",
  },
  {
    _id: "l7",
    book: mockBooks[6],
    seller: mockUsers[0],
    price: 350000,
    originalPrice: 780000,
    condition: {
      grade: "excellent",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img7", url: "", alt: "هندسه تحلیلی مبتکران", isPrimary: true }],
    description: "فقط یه بار خوندمش. تمیز و مرتب.",
    year: 1405,
    edition: 9,
    city: "تهران",
    province: "تهران",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 289,
    favorites: 22,
    status: "active",
    createdAt: "2026-07-05T08:00:00Z",
    updatedAt: "2026-07-05T08:00:00Z",
  },
  {
    _id: "l8",
    book: mockBooks[7],
    seller: mockUsers[6],
    price: 420000,
    originalPrice: 690000,
    condition: {
      grade: "acceptable",
      highlighting: true,
      handwrittenNotes: true,
      tornPages: false,
      missingPages: false,
      answersCompleted: true,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img8", url: "", alt: "حسابان دوازدهم خیلی سبز", isPrimary: true }],
    description: "استفاده شده ولی کامل و بدون صفحه کم. یادداشت‌ها و هایلایت زیاد.",
    year: 1404,
    edition: 11,
    city: "ساری",
    province: "مازندران",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "high",
    views: 98,
    favorites: 5,
    status: "active",
    createdAt: "2026-07-04T15:15:00Z",
    updatedAt: "2026-07-04T15:15:00Z",
  },
  {
    _id: "l9",
    book: mockBooks[8],
    seller: mockUsers[3],
    price: 200000,
    originalPrice: 560000,
    condition: {
      grade: "like-new",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img9", url: "", alt: "تاریخ ایران و جهان مدرسه", isPrimary: true }],
    description: "تازه خریده بودم ولی رشتم عوض شد. کاملاً نو.",
    year: 1405,
    edition: 4,
    city: "مشهد",
    province: "خراسان رضوی",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 445,
    favorites: 37,
    status: "active",
    createdAt: "2026-07-12T07:00:00Z",
    updatedAt: "2026-07-12T07:00:00Z",
  },
  {
    _id: "l10",
    book: mockBooks[10],
    seller: mockUsers[1],
    price: 480000,
    originalPrice: 750000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: true,
      hasSupplement: false,
    },
    images: [{ _id: "img10", url: "", alt: "زبان انگلیسی جامع گاج", isPrimary: true }],
    description: "DVD آموزشی سالمه. کتاب هایلایت شده ولی خوب خوانا هست.",
    year: 1404,
    edition: 5,
    city: "اصفهان",
    province: "اصفهان",
    shippingAvailable: true,
    pickupAvailable: false,
    isBundle: false,
    priceIndicator: "fair",
    views: 201,
    favorites: 14,
    status: "active",
    createdAt: "2026-07-03T12:00:00Z",
    updatedAt: "2026-07-03T12:00:00Z",
  },
  {
    _id: "l11",
    book: mockBooks[9],
    seller: mockUsers[4],
    price: 300000,
    originalPrice: 620000,
    condition: {
      grade: "excellent",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img11", url: "", alt: "فلسفه و منطق جامع الگو", isPrimary: true }],
    description: "وضعیت عالی. اصلاً استفاده نشده.",
    year: 1405,
    edition: 3,
    city: "کرج",
    province: "البرز",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 178,
    favorites: 12,
    status: "active",
    createdAt: "2026-07-11T16:30:00Z",
    updatedAt: "2026-07-11T16:30:00Z",
  },
  {
    _id: "l12",
    book: mockBooks[11],
    seller: mockUsers[5],
    price: 190000,
    originalPrice: 480000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img12", url: "", alt: "دین و زندگی جامع قلم‌چی", isPrimary: true }],
    description: "هایلایت شده. حالت کتاب خوبه.",
    year: 1404,
    edition: 6,
    city: "تبریز",
    province: "آذربایجان شرقی",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "great",
    views: 267,
    favorites: 21,
    status: "active",
    createdAt: "2026-07-10T09:45:00Z",
    updatedAt: "2026-07-10T09:45:00Z",
  },
  // Bundle listing
  {
    _id: "l13",
    book: mockBooks[0],
    seller: mockUsers[1],
    price: 2200000,
    originalPrice: 4150000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: true,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: true,
      hasSupplement: false,
    },
    images: [{ _id: "img13", url: "", alt: "پکیج کامل تجربی", isPrimary: true }],
    description:
      "پکیج کامل دروس اختصاصی تجربی شامل: زیست، شیمی، فیزیک و ریاضی. همه از ناشرهای معتبر.",
    year: 1404,
    edition: 0,
    city: "اصفهان",
    province: "اصفهان",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: true,
    bundleBooks: [mockBooks[0], mockBooks[1], mockBooks[2], mockBooks[3]],
    priceIndicator: "great",
    views: 823,
    favorites: 67,
    status: "active",
    createdAt: "2026-07-09T08:00:00Z",
    updatedAt: "2026-07-09T08:00:00Z",
  },
  {
    _id: "l14",
    book: mockBooks[4],
    seller: mockUsers[0],
    price: 1500000,
    originalPrice: 2710000,
    condition: {
      grade: "excellent",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img14", url: "", alt: "پکیج دروس عمومی", isPrimary: true }],
    description:
      "پکیج کامل دروس عمومی: ادبیات، عربی، زبان، دین و زندگی. وضعیت عالی، بدون خط‌خوردگی.",
    year: 1404,
    edition: 0,
    city: "تهران",
    province: "تهران",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: true,
    bundleBooks: [mockBooks[4], mockBooks[5], mockBooks[10], mockBooks[11]],
    priceIndicator: "great",
    views: 534,
    favorites: 41,
    status: "active",
    createdAt: "2026-07-08T10:30:00Z",
    updatedAt: "2026-07-08T10:30:00Z",
  },
  {
    _id: "l15",
    book: mockBooks[12],
    seller: mockUsers[6],
    price: 220000,
    originalPrice: 580000,
    condition: {
      grade: "like-new",
      highlighting: false,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: true,
      hasSupplement: false,
    },
    images: [{ _id: "img15", url: "", alt: "فیزیک پایه دهم خیلی سبز", isPrimary: true }],
    description: "کاملاً نو، خریدم ولی اصلاً استفاده نکردم. CD آموزشی سالم.",
    year: 1405,
    edition: 13,
    city: "ساری",
    province: "مازندران",
    shippingAvailable: true,
    pickupAvailable: false,
    isBundle: false,
    priceIndicator: "great",
    views: 312,
    favorites: 26,
    status: "active",
    createdAt: "2026-07-12T11:00:00Z",
    updatedAt: "2026-07-12T11:00:00Z",
  },
  {
    _id: "l16",
    book: mockBooks[16],
    seller: mockUsers[2],
    price: 320000,
    originalPrice: 540000,
    condition: {
      grade: "good",
      highlighting: true,
      handwrittenNotes: false,
      tornPages: false,
      missingPages: false,
      answersCompleted: false,
      coverDamaged: false,
      hasCd: false,
      hasSupplement: false,
    },
    images: [{ _id: "img16", url: "", alt: "روان‌شناسی جامع قلم‌چی", isPrimary: true }],
    description: "هایلایت شده ولی کاملاً خوانا. وضعیت خوب.",
    year: 1404,
    edition: 5,
    city: "شیراز",
    province: "فارس",
    shippingAvailable: true,
    pickupAvailable: true,
    isBundle: false,
    priceIndicator: "fair",
    views: 145,
    favorites: 9,
    status: "active",
    createdAt: "2026-07-07T14:20:00Z",
    updatedAt: "2026-07-07T14:20:00Z",
  },
];

// Helper to get featured/recent listings
export function getRecentListings(count = 8): Listing[] {
  return [...mockListings]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, count);
}

export function getBundleListings(): Listing[] {
  return mockListings.filter((l) => l.isBundle);
}

export function getListingsByField(field: string, count = 8): Listing[] {
  return mockListings.filter((l) => l.book.field === field).slice(0, count);
}

export function getListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l._id === id);
}

export function getRecommendedListings(count = 8): Listing[] {
  return [...mockListings]
    .sort((a, b) => b.views - a.views)
    .slice(0, count);
}

export function getSellerListings(sellerId: string): Listing[] {
  return mockListings.filter((l) => l.seller._id === sellerId);
}
