// Seed script: populate MongoDB with initial data
// Run with: npx tsx scripts/seed.ts

import mongoose from "mongoose";
import User from "../lib/models/User";
import Listing from "../lib/models/Listing";
import Publisher from "../lib/models/Publisher";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/konkoorbaz";

const publishers = [
  { name: "گاج", slug: "gaj", logo: "" },
  { name: "قلم‌چی", slug: "ghalam-chi", logo: "" },
  { name: "خیلی سبز", slug: "kheili-sabz", logo: "" },
  { name: "مگا بوک", slug: "mega-book", logo: "" },
  { name: "نشر الگو", slug: "nashr-olgu", logo: "" },
  { name: "مبتکران", slug: "mobtakeran", logo: "" },
  { name: "کانون فرهنگی آموزش", slug: "kanoon", logo: "" },
  { name: "مدرسه", slug: "madreseh", logo: "" },
  { name: "مهروماه", slug: "mehr-o-mah", logo: "" },
  { name: "میکرو طبقه‌بندی", slug: "micro", logo: "" },
  { name: "نردبان", slug: "nardebaan", logo: "" },
  { name: "خوشخوان", slug: "khoshkhaan", logo: "" },
];

const users = [
  {
    name: "محمد رضایی",
    phone: "09120004567",
    role: "user",
    isVerified: true,
    province: "تهران",
    city: "تهران",
    rating: 4.8,
    totalSales: 23,
    totalPurchases: 5,
  },
  {
    name: "زهرا احمدی",
    phone: "09350008901",
    role: "user",
    isVerified: true,
    province: "اصفهان",
    city: "اصفهان",
    rating: 4.9,
    totalSales: 45,
    totalPurchases: 12,
  },
  {
    name: "امیرعلی حسینی",
    phone: "09190002345",
    role: "user",
    isVerified: true,
    province: "فارس",
    city: "شیراز",
    rating: 4.6,
    totalSales: 15,
    totalPurchases: 8,
  },
  {
    name: "فاطمه موسوی",
    phone: "09220006789",
    role: "user",
    isVerified: false,
    province: "خراسان رضوی",
    city: "مشهد",
    rating: 4.3,
    totalSales: 7,
    totalPurchases: 3,
  },
  {
    name: "رضا کریمی",
    phone: "09360000123",
    role: "user",
    isVerified: true,
    province: "تهران",
    city: "کرج",
    rating: 4.7,
    totalSales: 31,
    totalPurchases: 9,
  },
  {
    name: "نازنین عباسی",
    phone: "09180004567",
    role: "user",
    isVerified: true,
    province: "آذربایجان شرقی",
    city: "تبریز",
    rating: 5.0,
    totalSales: 52,
    totalPurchases: 18,
  },
  {
    name: "حسین نوری",
    phone: "09130008910",
    role: "user",
    isVerified: true,
    province: "مازندران",
    city: "ساری",
    rating: 4.5,
    totalSales: 11,
    totalPurchases: 6,
  },
];

async function seed() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("Connected.\n");

  // Clear existing data
  await User.deleteMany({});
  await Listing.deleteMany({});
  await Publisher.deleteMany({});
  console.log("Cleared existing data.");

  // Seed publishers
  const createdPublishers = await Publisher.insertMany(publishers);
  console.log(`Seeded ${createdPublishers.length} publishers.`);

  // Seed users
  const createdUsers = await User.insertMany(users);
  console.log(`Seeded ${createdUsers.length} users.`);

  // Helper to get publisher by slug
  const pubBySlug = (slug: string) =>
    createdPublishers.find((p) => p.slug === slug)!;

  // Seed listings
  const listings = [
    {
      book: {
        title: "زیست‌شناسی جامع کنکور",
        author: "اشکان هاشمی",
        publisher: { name: pubBySlug("gaj").name, slug: "gaj" },
        field: "experimental",
        grade: "konkoor",
        subject: "biology",
        originalPrice: 980000,
      },
      seller: createdUsers[0]._id,
      price: 450000,
      originalPrice: 980000,
      condition: {
        grade: "excellent",
        highlighting: true,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: true,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "زیست‌شناسی جامع کنکور گاج", isPrimary: true }],
      description: "کتاب تمیز و سالم، فقط چند صفحه هایلایت شده. DVD آموزشی هم داره.",
      year: 1404,
      edition: 12,
      city: "تهران",
      province: "تهران",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 342,
      favorites: 28,
      status: "active",
    },
    {
      book: {
        title: "ریاضی تجربی جامع",
        author: "مهدی امینی‌راد",
        publisher: { name: pubBySlug("ghalam-chi").name, slug: "ghalam-chi" },
        field: "experimental",
        grade: "konkoor",
        subject: "math",
        originalPrice: 850000,
      },
      seller: createdUsers[1]._id,
      price: 520000,
      originalPrice: 850000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: true,
        tornPages: false,
        missingPages: false,
        answersCompleted: true,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "ریاضی تجربی جامع قلم‌چی", isPrimary: true }],
      description: "تست‌ها پاسخ داده شده ولی کتاب سالمه.",
      year: 1404,
      edition: 8,
      city: "اصفهان",
      province: "اصفهان",
      shippingAvailable: true,
      pickupAvailable: false,
      isBundle: false,
      priceIndicator: "fair",
      views: 189,
      favorites: 15,
      status: "active",
    },
    {
      book: {
        title: "فیزیک پایه دوازدهم",
        author: "محمد عبدالهی",
        publisher: { name: pubBySlug("kheili-sabz").name, slug: "kheili-sabz" },
        field: "experimental",
        grade: "12",
        subject: "physics",
        originalPrice: 720000,
      },
      seller: createdUsers[2]._id,
      price: 280000,
      originalPrice: 720000,
      condition: {
        grade: "like-new",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: true,
        hasSupplement: true,
      },
      images: [{ url: "", alt: "فیزیک پایه دوازدهم خیلی سبز", isPrimary: true }],
      description: "خریدم ولی از یکی دیگه استفاده کردم. اصلاً باز نشده تقریباً.",
      year: 1405,
      edition: 15,
      city: "شیراز",
      province: "فارس",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 567,
      favorites: 45,
      status: "active",
    },
    {
      book: {
        title: "شیمی جامع کنکور",
        author: "بهمن بازرگانی",
        publisher: { name: pubBySlug("gaj").name, slug: "gaj" },
        field: "experimental",
        grade: "konkoor",
        subject: "chemistry",
        originalPrice: 920000,
      },
      seller: createdUsers[3]._id,
      price: 550000,
      originalPrice: 920000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "شیمی جامع کنکور گاج", isPrimary: true }],
      description: "هایلایت شده ولی خیلی تمیز.",
      year: 1404,
      edition: 10,
      city: "مشهد",
      province: "خراسان رضوی",
      shippingAvailable: true,
      pickupAvailable: false,
      isBundle: false,
      priceIndicator: "fair",
      views: 234,
      favorites: 19,
      status: "active",
    },
    {
      book: {
        title: "ادبیات فارسی جامع",
        author: "علی‌اصغر حسینی",
        publisher: { name: pubBySlug("nashr-olgu").name, slug: "nashr-olgu" },
        field: "experimental",
        grade: "konkoor",
        subject: "persian",
        originalPrice: 650000,
      },
      seller: createdUsers[4]._id,
      price: 250000,
      originalPrice: 650000,
      condition: {
        grade: "excellent",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "ادبیات فارسی جامع نشر الگو", isPrimary: true }],
      description: "کاملاً سالم و تمیز.",
      year: 1404,
      edition: 6,
      city: "کرج",
      province: "البرز",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 412,
      favorites: 33,
      status: "active",
    },
    {
      book: {
        title: "عربی کامل کنکور",
        author: "حسین ادیب",
        publisher: { name: pubBySlug("ghalam-chi").name, slug: "ghalam-chi" },
        field: "experimental",
        grade: "konkoor",
        subject: "arabic",
        originalPrice: 580000,
      },
      seller: createdUsers[5]._id,
      price: 380000,
      originalPrice: 580000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: true,
        tornPages: false,
        missingPages: false,
        answersCompleted: true,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "عربی کامل کنکور قلم‌چی", isPrimary: true }],
      description: "تست‌ها جواب داده شده.",
      year: 1403,
      edition: 7,
      city: "تبریز",
      province: "آذربایجان شرقی",
      shippingAvailable: true,
      pickupAvailable: false,
      isBundle: false,
      priceIndicator: "high",
      views: 156,
      favorites: 8,
      status: "active",
    },
    {
      book: {
        title: "هندسه تحلیلی و جبر خطی",
        author: "احمد صادقی",
        publisher: { name: pubBySlug("mobtakeran").name, slug: "mobtakeran" },
        field: "mathematics",
        grade: "12",
        subject: "geometry",
        originalPrice: 780000,
      },
      seller: createdUsers[0]._id,
      price: 350000,
      originalPrice: 780000,
      condition: {
        grade: "excellent",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "هندسه تحلیلی مبتکران", isPrimary: true }],
      description: "فقط یه بار خوندمش.",
      year: 1405,
      edition: 9,
      city: "تهران",
      province: "تهران",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 289,
      favorites: 22,
      status: "active",
    },
    {
      book: {
        title: "حسابان دوازدهم",
        author: "مصطفی باقری",
        publisher: { name: pubBySlug("kheili-sabz").name, slug: "kheili-sabz" },
        field: "mathematics",
        grade: "12",
        subject: "math",
        originalPrice: 690000,
      },
      seller: createdUsers[6]._id,
      price: 420000,
      originalPrice: 690000,
      condition: {
        grade: "acceptable",
        highlighting: true,
        handwrittenNotes: true,
        tornPages: false,
        missingPages: false,
        answersCompleted: true,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "حسابان دوازدهم خیلی سبز", isPrimary: true }],
      description: "استفاده شده ولی کامل.",
      year: 1404,
      edition: 11,
      city: "ساری",
      province: "مازندران",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "high",
      views: 98,
      favorites: 5,
      status: "active",
    },
    {
      book: {
        title: "تاریخ ایران و جهان",
        author: "مریم افشار",
        publisher: { name: pubBySlug("madreseh").name, slug: "madreseh" },
        field: "humanities",
        grade: "konkoor",
        subject: "history",
        originalPrice: 560000,
      },
      seller: createdUsers[3]._id,
      price: 200000,
      originalPrice: 560000,
      condition: {
        grade: "like-new",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "تاریخ ایران و جهان مدرسه", isPrimary: true }],
      description: "تازه خریده بودم ولی رشتم عوض شد.",
      year: 1405,
      edition: 4,
      city: "مشهد",
      province: "خراسان رضوی",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 445,
      favorites: 37,
      status: "active",
    },
    {
      book: {
        title: "زبان انگلیسی جامع کنکور",
        author: "فرشید یوسفی",
        publisher: { name: pubBySlug("gaj").name, slug: "gaj" },
        field: "experimental",
        grade: "konkoor",
        subject: "english",
        originalPrice: 750000,
      },
      seller: createdUsers[1]._id,
      price: 480000,
      originalPrice: 750000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: true,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "زبان انگلیسی جامع گاج", isPrimary: true }],
      description: "DVD آموزشی سالمه.",
      year: 1404,
      edition: 5,
      city: "اصفهان",
      province: "اصفهان",
      shippingAvailable: true,
      pickupAvailable: false,
      isBundle: false,
      priceIndicator: "fair",
      views: 201,
      favorites: 14,
      status: "active",
    },
    {
      book: {
        title: "فلسفه و منطق جامع",
        author: "کامران رحیمی",
        publisher: { name: pubBySlug("nashr-olgu").name, slug: "nashr-olgu" },
        field: "humanities",
        grade: "konkoor",
        subject: "philosophy",
        originalPrice: 620000,
      },
      seller: createdUsers[4]._id,
      price: 300000,
      originalPrice: 620000,
      condition: {
        grade: "excellent",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "فلسفه و منطق جامع الگو", isPrimary: true }],
      description: "وضعیت عالی. اصلاً استفاده نشده.",
      year: 1405,
      edition: 3,
      city: "کرج",
      province: "البرز",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 178,
      favorites: 12,
      status: "active",
    },
    {
      book: {
        title: "دین و زندگی جامع",
        author: "سعید محمدی",
        publisher: { name: pubBySlug("ghalam-chi").name, slug: "ghalam-chi" },
        field: "experimental",
        grade: "konkoor",
        subject: "religion",
        originalPrice: 480000,
      },
      seller: createdUsers[5]._id,
      price: 190000,
      originalPrice: 480000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "دین و زندگی جامع قلم‌چی", isPrimary: true }],
      description: "هایلایت شده. حالت کتاب خوبه.",
      year: 1404,
      edition: 6,
      city: "تبریز",
      province: "آذربایجان شرقی",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "great",
      views: 267,
      favorites: 21,
      status: "active",
    },
    {
      book: {
        title: "فیزیک پایه دهم",
        author: "رضا ناظمی",
        publisher: { name: pubBySlug("kheili-sabz").name, slug: "kheili-sabz" },
        field: "experimental",
        grade: "10",
        subject: "physics",
        originalPrice: 580000,
      },
      seller: createdUsers[6]._id,
      price: 220000,
      originalPrice: 580000,
      condition: {
        grade: "like-new",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: true,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "فیزیک پایه دهم خیلی سبز", isPrimary: true }],
      description: "کاملاً نو، خریدم ولی اصلاً استفاده نکردم.",
      year: 1405,
      edition: 13,
      city: "ساری",
      province: "مازندران",
      shippingAvailable: true,
      pickupAvailable: false,
      isBundle: false,
      priceIndicator: "great",
      views: 312,
      favorites: 26,
      status: "active",
    },
    {
      book: {
        title: "روان‌شناسی جامع کنکور",
        author: "لیلا شهبازی",
        publisher: { name: pubBySlug("ghalam-chi").name, slug: "ghalam-chi" },
        field: "humanities",
        grade: "konkoor",
        subject: "psychology",
        originalPrice: 540000,
      },
      seller: createdUsers[2]._id,
      price: 320000,
      originalPrice: 540000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "روان‌شناسی جامع قلم‌چی", isPrimary: true }],
      description: "هایلایت شده ولی کاملاً خوانا.",
      year: 1404,
      edition: 5,
      city: "شیراز",
      province: "فارس",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: false,
      priceIndicator: "fair",
      views: 145,
      favorites: 9,
      status: "active",
    },
    // Bundle listings
    {
      book: {
        title: "پکیج کامل تجربی",
        author: "گروه مولفان",
        publisher: { name: pubBySlug("gaj").name, slug: "gaj" },
        field: "experimental",
        grade: "konkoor",
        subject: "biology",
        originalPrice: 4150000,
      },
      seller: createdUsers[1]._id,
      price: 2200000,
      originalPrice: 4150000,
      condition: {
        grade: "good",
        highlighting: true,
        handwrittenNotes: true,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: true,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "پکیج کامل تجربی", isPrimary: true }],
      description: "پکیج کامل دروس اختصاصی تجربی شامل: زیست، شیمی، فیزیک و ریاضی.",
      year: 1404,
      edition: 0,
      city: "اصفهان",
      province: "اصفهان",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: true,
      bundleBooks: [
        { title: "زیست‌شناسی جامع کنکور", author: "اشکان هاشمی", publisher: { name: "گاج", slug: "gaj" }, field: "experimental", grade: "konkoor", subject: "biology", originalPrice: 980000 },
        { title: "ریاضی تجربی جامع", author: "مهدی امینی‌راد", publisher: { name: "قلم‌چی", slug: "ghalam-chi" }, field: "experimental", grade: "konkoor", subject: "math", originalPrice: 850000 },
        { title: "فیزیک پایه دوازدهم", author: "محمد عبدالهی", publisher: { name: "خیلی سبز", slug: "kheili-sabz" }, field: "experimental", grade: "12", subject: "physics", originalPrice: 720000 },
        { title: "شیمی جامع کنکور", author: "بهمن بازرگانی", publisher: { name: "گاج", slug: "gaj" }, field: "experimental", grade: "konkoor", subject: "chemistry", originalPrice: 920000 },
      ],
      priceIndicator: "great",
      views: 823,
      favorites: 67,
      status: "active",
    },
    {
      book: {
        title: "پکیج دروس عمومی",
        author: "گروه مولفان",
        publisher: { name: pubBySlug("nashr-olgu").name, slug: "nashr-olgu" },
        field: "experimental",
        grade: "konkoor",
        subject: "persian",
        originalPrice: 2710000,
      },
      seller: createdUsers[0]._id,
      price: 1500000,
      originalPrice: 2710000,
      condition: {
        grade: "excellent",
        highlighting: false,
        handwrittenNotes: false,
        tornPages: false,
        missingPages: false,
        answersCompleted: false,
        coverDamaged: false,
        hasCd: false,
        hasSupplement: false,
      },
      images: [{ url: "", alt: "پکیج دروس عمومی", isPrimary: true }],
      description: "پکیج کامل دروس عمومی: ادبیات، عربی، زبان، دین و زندگی.",
      year: 1404,
      edition: 0,
      city: "تهران",
      province: "تهران",
      shippingAvailable: true,
      pickupAvailable: true,
      isBundle: true,
      bundleBooks: [
        { title: "ادبیات فارسی جامع", author: "علی‌اصغر حسینی", publisher: { name: "نشر الگو", slug: "nashr-olgu" }, field: "experimental", grade: "konkoor", subject: "persian", originalPrice: 650000 },
        { title: "عربی کامل کنکور", author: "حسین ادیب", publisher: { name: "قلم‌چی", slug: "ghalam-chi" }, field: "experimental", grade: "konkoor", subject: "arabic", originalPrice: 580000 },
        { title: "زبان انگلیسی جامع کنکور", author: "فرشید یوسفی", publisher: { name: "گاج", slug: "gaj" }, field: "experimental", grade: "konkoor", subject: "english", originalPrice: 750000 },
        { title: "دین و زندگی جامع", author: "سعید محمدی", publisher: { name: "قلم‌چی", slug: "ghalam-chi" }, field: "experimental", grade: "konkoor", subject: "religion", originalPrice: 480000 },
      ],
      priceIndicator: "great",
      views: 534,
      favorites: 41,
      status: "active",
    },
  ];

  const createdListings = await Listing.insertMany(listings);
  console.log(`Seeded ${createdListings.length} listings.`);

  console.log("\nSeed complete!");
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
